server:
  port: ${PORT:8080}

spring:
  application:
    name: market-hub

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:marketHub_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true

logging:
  config: classpath:log4j2.properties
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

init:
  database: false

app:
  jwt:
    secret: ${JWT_SECRET:vo0JQPx0rXk$g%JG@J8XAR734PrK#*^sUAS8VDum^N*!7bjmUW/XN2LNg9Q5gy5Ew&jrTp%y^2D_}
    expire: ${JWT_EXPIRE:864000000}

minio:
  url: http://localhost:9000
  console-url: http://localhost:9001
  access-key: admin
  secret-key: admin123
  bucket: test
  expiry-seconds: ${MINIO_EXPIRY_SECONDS:30}